### ISSUE TITLE
Can the license be changed to a software license?

### ISSUE THREAD

**Issue by aag** [TurtleEntertainment/aiur#2]
Aiur is currently licensed under a CC BY-SA 3.0 license.  However, the Creative Commons says that "Creative Commons licenses should not be used for software."  CC licenses were not designed for use with software and don't address all of the legal issues of software.

Could the aiur code be relicensed under a software-specific license such as the MIT, BSD, GPL, or LGPL licenses?

http://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F

**Comment by basert** [comment]
changed license to MIT
